import {
  OverviewData,
  UrlParams,
  Aggregated,
  Period,
  DeviceData,
  TopPagesData,
} from '../utils/types';
import { toUrlParams } from '../utils/common';

const BASE_URL = '/api/piwik-dashboard';

/**
 * fetchData function sends all API requests to
 * retrieve data from the Piwik PRO drupal module
 *
 * @param baseUrl - The base URL for the API endpoint
 * @param params - The parameters to be sent with the request
 * @returns - The fetched data or null if an error occurs
 */
const fetchData = async (baseUrl: string, params: UrlParams) => {
  try {
    const paramsString = toUrlParams(params);
    const url = paramsString ? `${baseUrl}?${paramsString}` : baseUrl;
    const response = await fetch(url);

    if (!response.ok) {
      throw new Error(`API error: ${response.status} ${response.statusText}`);
    }

    const data = await response.json();

    if (data && Array.isArray(data.data)) {
      return data.data;
    } else {
      console.warn('Unexpected data format:', data);
      return null;
    }
  } catch (error) {
    console.error('Failed to fetch Piwik PRO data:', error);
    return null;
  }
};

/**
 * Fetches overview data, such as visitors, page views,
 * returning visitors rate and bounce rate
 *
 * @param aggregated - Aggregated data flag
 * @param range - Time range for the data
 * @returns - Overview data or null if an error occurs
 */
export const fetchOverviewData = async (
  aggregated: Aggregated,
  range: Period,
): Promise<OverviewData[] | null> => {
  const url = `${BASE_URL}/overview`;
  return await fetchData(url, {
    aggregated,
    range,
  });
};

/**
 * Fetches device data, such as device type and how many sessions
 * were generated by each device
 *
 * @param range - Time range for the data
 * @returns - Device data or null if an error occurs
 */
export const fetchDeviceData = async (
  range: Period,
): Promise<DeviceData[] | null> => {
  const url = `${BASE_URL}/devices`;
  return await fetchData(url, { range });
};

/**
 * Fetches top pages data, such as page URL and how many page views
 * each top page had
 * @param range - Time range for the data
 * @returns - Top pages data or null if an error occurs
 */
export const fetchTopPagesData = async (
  range: Period,
): Promise<TopPagesData[] | null> => {
  const url = `${BASE_URL}/top-pages`;
  return await fetchData(url, { range });
};
